services:

  #contenedor de la bd de postgres la cual uso es 15-alpine que es más ligera
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - database_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # pgadmin como gestor de bd
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    #      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - datos_pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  # app con springboot - descomentar cuando quiera levantar la app
  stock-ms:
    container_name: springboot-app
    image: sb-app
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8095:8080"

# aquí ponemos los volúmenes
volumes:
  database_postgres:
  datos_pgadmin: